### ISSUE TITLE
New feature - replace Hue

### ISSUE THREAD

**Issue by alanontheweb** [lewishowles/sketch-replace-colour#18]
Hello,

Unfortunately, I haven't been able to maintain the forked plugin and have been getting asked about it from some folks. Do you think this is something you can bake into your plugin?

http://bit.ly/2neKALu

Thanks!

**Comment by rodnem** [comment]
PLEASE do it:)
This option to switch the HUE value is great!
Look @alanontheweb demo on youtube: https://www.youtube.com/watch?v=rigA5znlYp0&index=26&list=WL

But it would be great if we could change the hue, not by name but using digits between 1 and 360

**Comment by alanontheweb** [comment]
@rodnem that was possible in the forked plugin on my page as well (using values of 1 to 360). In the demo, I just used the "green" name for simplicity.

@lewishowles I know color management can be done intelligently through nested symbols right now as well, but they don't provide an easy way to add modifier colors (based off the base colors) that can be read in  properly by tools like Avocode properly.

**Comment by rodnem** [comment]
@alanontheweb 
The color symbols trick is not really great. For example, your svg will not be optimized.
Your technic is by far more cleaner

**Comment by alanontheweb** [comment]
Yeah, it also gets read much better by these third party tools.

**Comment by lewishowles** [comment]
Sorry for the delay, not had any time to even use Sketch lately.

I've just committed version 2.1 and 2.1.1, which I believe adds this functionality. It's a new option at the bottom that will default to Colour, but if you change to Hue it'll kick in hue replacements instead.

As of 2.1.1 you can now also enter a hue value, as well as a hex, when replacing hue.

I had to change quite a lot of the original code from your fork since Sketch keep changing what functions they support (🤦) but hopefully it'll do the trick.

**Comment by alanontheweb** [comment]
Wow, thanks Lewis! I'll give this a try soon and retire my fork later this weekend with a link to your page :)

**Comment by rodnem** [comment]
It works great !
